# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --name bt4222_hotels > environment.yml
#    conda env remove --name bt4222_hotels
#    conda env list

name: bt4222_hotels
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip=23.2.1
  - pip:
      - bottleneck
      - numpy
      - pandas
      - ipykernel
      - ipython
      - matplotlib
      - pyprojroot
      - scikit-learn
      - nltk
      - vaderSentiment
      - textblob
      - spacy
      - jupyter-client
      - jupyter-core
      - PyPDF2
      - transformers